name: Publish Package
on:
  release:
    types: [published]
jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Setup .npmrc file to publish to npm
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install deps and build
        run: yarn install
        
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
    
